pygments: true
markdown: rdiscount
lsi: true
permalink: /:categories/:year/:month/:day/:title.html
description: "Personal website for Lewis Oaten."
keywords: - Lewis
          - Oaten
	  - Programming
	  - Development
	  - Software
	  - Engineering
	  - Code
	  - SVN
	  - Git
	  - Scrum
	  - XP
	  - Computing
main_title: "Lewis Oaten"
